AbstractSubcriber: Fix FloggerFormatString pattern flagged by error prone
Build is failing with recent Error Prone version:

  AbstractSubcriber.java:79: error: [FloggerFormatString]
  missing argument for format specifier '%s'
        logger.atSevere().withCause(e).log(
                                          ^
    (see https://errorprone.info/bugpattern/FloggerFormatString)

Change-Id: I254a4c78f80feaab6f92eae306a7a2047ecccbd1