Update patch set 1
Patch Set 1:

> Patch Set 1: Verified-1
> 
> This doesn't build here:
> 
>   plugins/multi-site/src/main/java/com/googlesource/gerrit/plugins/multisite/Module.java:50: error: cannot find symbol
>   @ModuleImpl(name = GitRepositoryManager.LOCAL_REPOSITORY_MODULE)
>                                        ^
>   symbol:   variable LOCAL_REPOSITORY_MODULE
>   location: interface GitRepositoryManager
> 
> What am I missing?

I think I see what happened. The build breakage was introduced in Ic465e48a14376bb97e8ec10d69df66a5de87e201. In the commit message it is stated:

Requires Gerrit change I5b5a9432eb3db2559ce6a4393a42a4d227a371b5.

However, this change: [1] was never merged. And this is a left over:

  @ModuleImpl(name = GitRepositoryManager.LOCAL_REPOSITORY_MODULE)

from this attempt to fix lib module loading.

[1] https://gerrit-review.googlesource.com/c/gerrit/+/220854

Patch-set: 1
Reviewer: Gerrit User 1011323 <1011323@173816e5-2b9a-37c3-8a2e-48639d4f1153>