Update patch set 1
Patch Set 1: Verified-1

This doesn't build here:

  plugins/multi-site/src/main/java/com/googlesource/gerrit/plugins/multisite/Module.java:50: error: cannot find symbol
  @ModuleImpl(name = GitRepositoryManager.LOCAL_REPOSITORY_MODULE)
                                       ^
  symbol:   variable LOCAL_REPOSITORY_MODULE
  location: interface GitRepositoryManager

What am I missing?

Patch-set: 1
Reviewer: Gerrit User 1006192 <1006192@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Reviewer: Gerrit User 1011323 <1011323@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=-1