Configuration: Fix MutableConstantField warning
When all error prone warnings are enabled the MutableConstantField bug
pattern is reported:

Configuration.java:264: error: [MutableConstantField] Constant field \
declarations should use the immutable type (such as ImmutableList) \
instead of the general collection interface type (such as List)
    private static final Map<EventFamily, String> EVENT_TOPICS =
                            ^
    (see https://errorprone.info/bugpattern/MutableConstantField)

Change-Id: Ibf156301c2c15cedd1346289675a1871700ca47d