Update patch set 1
Patch Set 1: Code-Review-1

I'm getting exception when I'm trying to run this code:
[2019-07-25 22:14:19,738] [HTTP-94] ERROR com.googlesource.gerrit.plugins.multisite.Log4jSharedRefLogger : Cannot log sharedRefDB interaction for ref refs/sequences/changes on project All-Projects                                    
org.eclipse.jgit.errors.IncorrectObjectTypeException: Object b5045cc4046dbc1d7cafa4c603fd3cdf35dc5dde is not a commit.                                                                                                                  
        at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:802)                                                                                                                                                               
        at com.googlesource.gerrit.plugins.multisite.Log4jSharedRefLogger.logRefUpdate(Log4jSharedRefLogger.java:58)

I've run multi-site local environment and that I have created change from the UI

Patch-set: 1
Reviewer: Gerrit User 1083454 <1083454@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Code-Review=-1