DefaultSharedRefEnforcement: Fix MutableConstantField warning
When all error prone warnings are enabled the MutableConstantField bug
pattern is reported:

DefaultSharedRefEnforcement.java:23: error: [MutableConstantField] \
Constant field declarations should use the immutable type (such as \
ImmutableList) instead of the general collection interface type (such \
as List)
  private static final Map<String, EnforcePolicy> PREDEF_ENFORCEMENTS =
                          ^
    (see https://errorprone.info/bugpattern/MutableConstantField)

Change-Id: I7ab0d694c236cbcadb07b5efa1db0019f12be469