FileBasedWebSessionCacheTest: Fix IncompatibleArgumentType error
Compilation of the tests under bazel fails with:

  error: [IncompatibleArgumentType]
    Argument 'path' should not be passed to this method.
    Its type Path is not compatible with the required type: String.
      assertThat(cache.getIfPresent(path)).isNull();
                                    ^
      (see http://errorprone.info/bugpattern/IncompatibleArgumentType)

Change-Id: I97ca1f2242ffe0d1698ccb0c2c792fdb12169d3d