CachePatternMatcher: Fix MutableConstantField warning
When all error prone warnings are enabled the MutableConstantField bug
pattern is reported:

CachePatternMatcher.java:28: error: [MutableConstantField] Constant \
field declarations should use the immutable type (such as \
ImmutableList) instead of the general collection interface type (such \
as List)
  private static final List<String> DEFAULT_PATTERNS =
                           ^
    (see https://errorprone.info/bugpattern/MutableConstantField)

Change-Id: I5911f7e75c972c4aa58bbd11232b10ff477b11ed