Update patch set 7
Patch Set 7:

> Patch Set 6:
> 
> > Patch Set 6:
> > 
> > > Patch Set 6: Code-Review-1
> > > 
> > > I have tried to execute locally but I'm getting an error.
> > > Steps executed:
> > > - RUN: make init_all inside dockerised_local_env
> > > 
> > > ERROR:
> > > "...
> > > OK: 150 MiB in 81 packages
> > > fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
> > > fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
> > > (1/1) Installing git-daemon (2.20.1-r0)
> > > OK: 154 MiB in 82 packages
> > > Removing intermediate container 839f953e7055
> > >  ---> 0ca3d4785c5e
> > > Step 3/11 : COPY --chown=gerrit:gerrit bin/release.war /var/gerrit/bin/gerrit.war
> > > ERROR: Service 'gerrit-2' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder034822230/bin/release.war: no such file or directory
> > > make: *** [init_all] Error 1
> > > "
> > 
> > I can see that is looking for the bin/release.war. Do I need to provide this?
> 
> I have updated the Makefile to fix this issue and download the war before starting the services.

I can now start the docker containers and clone via http. I'm having an issue with the ssh keys when I try to clone via ssh. Is there a step I'm missing?

Patch-set: 7
Reviewer: Gerrit User 1065251 <1065251@173816e5-2b9a-37c3-8a2e-48639d4f1153>