Update patch set 2
Patch Set 2:

I have tried the whole chain of changes and worked for me. I could see me replication lag going up and back to 0 by creating a batch of changes.

Only thing I could see is this error when creating a new repo:

[2020-02-22 09:59:11,297] [kafka-subscriber-3] ERROR com.googlesource.gerrit.plugins.multisite.validation.ProjectVersionRefUpdate : Cannot read local project 'mama' version
org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: Cannot open repository mama
	at com.google.gerrit.server.git.LocalDiskRepositoryManager.openRepository(LocalDiskRepositoryManager.java:144)
	at com.google.gerrit.server.git.LocalDiskRepositoryManager.openRepository(LocalDiskRepositoryManager.java:132)
	at com.googlesource.gerrit.plugins.multisite.validation.MultiSiteGitRepositoryManager.openRepository(MultiSiteGitRepositoryManager.java:44)
	at com.googlesource.gerrit.plugins.multisite.validation.ProjectVersionRefUpdate.getProjectLocalVersion(ProjectVersionRefUpdate.java:252)
	at com.googlesource.gerrit.plugins.multisite.consumer.SubscriberMetrics.updateReplicationLagMetrics(SubscriberMetrics.java:116)
	at com.googlesource.gerrit.plugins.multisite.consumer.SubscriberMetrics.updateReplicationStatusMetrics(SubscriberMetrics.java:109)
	at com.googlesource.gerrit.plugins.multisite.consumer.AbstractSubcriber.processRecord(AbstractSubcriber.java:77)
	at com.googlesource.gerrit.plugins.kafka.subscribe.KafkaEventSubscriber$ReceiverJob.lambda$consume$0(KafkaEventSubscriber.java:122)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.googlesource.gerrit.plugins.kafka.subscribe.KafkaEventSubscriber$ReceiverJob.consume(KafkaEventSubscriber.java:117)
	at com.googlesource.gerrit.plugins.kafka.subscribe.KafkaEventSubscriber$ReceiverJob.run(KafkaEventSubscriber.java:106)
	at com.google.gerrit.server.logging.LoggingContextAwareRunnable.run(LoggingContextAwareRunnable.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at com.google.gerrit.server.git.WorkQueue$Task.run(WorkQueue.java:610)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /private/tmp/gerrit_setup/instance-2/git/mama
	at org.eclipse.jgit.lib.RepositoryCache$FileKey.open(RepositoryCache.java:445)
	at org.eclipse.jgit.lib.RepositoryCache.openRepository(RepositoryCache.java:278)
	at org.eclipse.jgit.lib.RepositoryCache.open(RepositoryCache.java:120)
	at org.eclipse.jgit.lib.RepositoryCache.open(RepositoryCache.java:93)
	at com.google.gerrit.server.git.LocalDiskRepositoryManager.openRepository(LocalDiskRepositoryManager.java:142)
	... 19 more 

It is probably just the case of handling the case of new repo (when there is no local version) correctly. But the rest of the functionality look ok.

Patch-set: 2
Reviewer: Gerrit User 1054778 <1054778@173816e5-2b9a-37c3-8a2e-48639d4f1153>